package com.bookmyconsultation.paymentservice.security;

public enum ApplicationPermission {
    DOCTOR_APPROVAL,
    DOCTOR_REJECTION,
    DOCTOR_REGISTRATION,
    DOCTOR_DOCUMENTS_UPLOAD,
    DOCTORS_LIST_VIEW,
    DOCTOR_VIEW,
    DOCTOR_DOCUMENTS_UPLOADED_VIEW,
    DOCTOR_DOCUMENTS_DOWNLOAD,
    USER_REGISTRATION,
    USER_DETAILS_VIEW,
    USER_DOCUMENTS_UPLOAD,
    USER_DOCUMENTS_DOWNLOAD,
    USER_DOCUMENTS_UPLOADED_VIEW,
    DOCTOR_AVAILABILITY_UPDATE,
    DOCTOR_AVAILABILITY_VIEW,
    BOOK_DOCTOR_APPOINTMENT,
    APPOINTMENT_DETAILS_VIEW,
    USER_APPOINTMENTS_VIEW,
    PRESCRIPTION_UPLOAD,
    PAYMENT_FOR_APPOINTMENT,
    RATE_DOCTOR
}
